# action.yml
name: 'Akto code analysis'
description: 'Discover API endpoints in source code'
inputs:
  AKTO_DASHBOARD_URL:  
    description: 'Akto dashboard URL'
    required: true
  AKTO_API_KEY:
    description: 'Akto API key'
    required: true
  API_COLLECTION_NAME:
    description: 'API collection name'
    required: true
runs:
  using: 'docker'
  image: 'docker://orenakto/akto-utils:latest'
  entrypoint: "node"
  args:
    - "/usr/app/build/apps/index.js"
    - "cli"
    - "extract"
    - "--PROJECT_DIR=/github/workspace"
    - "--AKTO_SYNC=true"
    - "--AKTO_DASHBOARD_URL=${{ inputs.AKTO_DASHBOARD_URL }}"
    - "--AKTO_API_KEY=${{ inputs.AKTO_API_KEY }}"
    - "--API_COLLECTION_NAME=${{ inputs.API_COLLECTION_NAME }}"
