name: 'Akto CI/CD'
description: 'Run akto in ci/cd'
inputs:
  # AKTO_DASHBOARD_URL:  
  #   required: true
  # AKTO_ACCESS_TOKEN:  
  #   required: true
  # AKTO_TEST_CONFIGURATION:  
  #   required: true
runs:
  using: 'node16'
  main: 'index.js'